name: gh-pages

on:
  push:
    branches:
      - master
      - develop
  release:
    types: [published]
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build-and-deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup deno
        uses: denolib/setup-deno@v2
        with:
          deno-version: v1.7.4

      - name: Build
        run: |
          export DENO_INSTALL="/home/runner/.deno"
          export PATH="$DENO_INSTALL/bin:$PATH"
          deno --version
          deno run --allow-net --allow-write --allow-read --allow-env ./mod.ts -u $USERNAME -t $TOKEN -f markdown
          sleep 3m
          deno install --unstable --allow-read --allow-write --allow-net --allow-run -n pagic https://raw.githubusercontent.com/xcatliu/pagic/v1.2.0/mod.ts
          pagic build
        env:
          USERNAME: ${{ secrets.USERNAME }}
          TOKEN: ${{ secrets.TOKEN }}

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          user_name: gh-action-for-pages
          user_email: gh-action@run.com
